#include "Shader.h"

#include <cstdio>
#include <cstring>
#include <fstream>
#include <iostream>

Shader::Shader()
    : shader(0)
{
}

Shader::~Shader()
{
    ClearShader();
}

void Shader::CreateFromFiles(const std::filesystem::path& vertexLocation,
                             const std::filesystem::path& fragmentLocation)
{
    const std::string vertexString = ReadFile(vertexLocation);
    const std::string fragmentString = ReadFile(fragmentLocation);

    if (vertexString.empty() || fragmentString.empty())
    {
        std::fprintf(stderr, "Shader source file is empty or could not be read.\n");
        return;
    }

    CompileShaders(vertexString.c_str(), fragmentString.c_str());
}

std::string Shader::ReadFile(const std::filesystem::path& fileLocation)
{
    std::ifstream fileStream(fileLocation);
    if (!fileStream.is_open())
    {
        std::cerr << "Failed to read shader file: " << fileLocation
                  << "\nThe path is generated by CMake from this repository's Shaders folder.\n";
        return {};
    }

    std::string content;
    std::string line;
    while (std::getline(fileStream, line))
    {
        content += line;
        content += '\n';
    }

    return content;
}

void Shader::UseShader()
{
    glUseProgram(shader);
}

void Shader::ClearShader()
{
    if (shader != 0)
    {
        glDeleteProgram(shader);
        shader = 0;
    }
}

void Shader::CreateFromString(const char* vertexCode, const char* fragmentCode)
{
    CompileShaders(vertexCode, fragmentCode);
}

void Shader::CompileShaders(const char* vertexCode, const char* fragmentCode)
{
    ClearShader();

    shader = glCreateProgram();
    if (shader == 0)
    {
        std::fprintf(stderr, "Error creating shader program.\n");
        return;
    }

    if (!AddShader(shader, vertexCode, GL_VERTEX_SHADER) ||
        !AddShader(shader, fragmentCode, GL_FRAGMENT_SHADER))
    {
        ClearShader();
        return;
    }

    glLinkProgram(shader);

    GLint result = 0;
    glGetProgramiv(shader, GL_LINK_STATUS, &result);
    if (!result)
    {
        GLchar errorLog[1024] = {};
        glGetProgramInfoLog(shader, sizeof(errorLog), nullptr, errorLog);
        std::fprintf(stderr, "Error linking shader program: %s\n", errorLog);
        ClearShader();
    }
}

bool Shader::AddShader(GLuint theProgram, const char* shaderCode, GLenum shaderType)
{
    const GLuint theShader = glCreateShader(shaderType);
    if (theShader == 0)
    {
        std::fprintf(stderr, "Error creating shader object.\n");
        return false;
    }

    const GLchar* code[] = { shaderCode };
    const GLint codeLength[] = { static_cast<GLint>(std::strlen(shaderCode)) };

    glShaderSource(theShader, 1, code, codeLength);
    glCompileShader(theShader);

    GLint result = 0;
    glGetShaderiv(theShader, GL_COMPILE_STATUS, &result);
    if (!result)
    {
        GLchar errorLog[1024] = {};
        glGetShaderInfoLog(theShader, sizeof(errorLog), nullptr, errorLog);
        std::fprintf(stderr, "Error compiling shader type %u: %s\n", shaderType, errorLog);
        glDeleteShader(theShader);
        return false;
    }

    glAttachShader(theProgram, theShader);
    // Safe after attachment: OpenGL keeps the shader alive until it is no longer attached.
    glDeleteShader(theShader);
    return true;
}
